from __future__ import annotations

from .models import Case, Evidence, InvoiceLine, RevenueSchedule, Usage


POLICIES = [
    Evidence(
        "POL-REV-001",
        "policy",
        "Revenue recognition five-step model",
        "Revenue recognition follows a five-step model: identify the contract, identify performance obligations, determine transaction price, allocate transaction price to performance obligations, and recognize revenue when or as obligations are satisfied.",
        "REV-ASC606-DEMO",
        "evidence://policy/POL-REV-001",
    ),
    Evidence(
        "POL-REV-002",
        "policy",
        "Ratable subscription treatment",
        "Subscription services are recognized ratably over the service period. Upfront billing does not by itself create immediate revenue recognition.",
        "REV-SUBSCRIPTION-DEMO",
        "evidence://policy/POL-REV-002",
    ),
    Evidence(
        "POL-REV-003",
        "policy",
        "Service credit treatment",
        "Approved service credits reduce billable consideration. If the credit relates to a specific module, apply the credit against that module unless a controller-approved exception exists.",
        "REV-CREDITS-DEMO",
        "evidence://policy/POL-REV-003",
    ),
    Evidence(
        "POL-REV-004",
        "policy",
        "Usage overage approval",
        "Usage overage revenue is recognized when usage occurs and the amount is billable under the contract. If contract terms require written approval before billing, route to billing hold until approval evidence exists.",
        "REV-USAGE-DEMO",
        "evidence://policy/POL-REV-004",
    ),
    Evidence(
        "POL-REV-006",
        "policy",
        "Approval thresholds",
        "Billing adjustments above $2,500 require billing manager approval. Revenue adjustments above $5,000 require controller approval. Any high-risk signal requires human review.",
        "REV-APPROVALS-DEMO",
        "evidence://policy/POL-REV-006",
    ),
    Evidence(
        "POL-REV-008",
        "policy",
        "Evidence required",
        "Every adjustment proposal must include evidence for contract terms, invoice lines, credits or usage, policy basis, proposed amount, and approval path.",
        "REV-EVIDENCE-DEMO",
        "evidence://policy/POL-REV-008",
    ),
]


CASES: list[Case] = [
    Case(
        case_id="C2C-1001",
        customer="Acme Robotics",
        customer_id="CUST-ACME",
        contract_id="CON-ACME-2026",
        invoice_id="INV-ACME-2026-05",
        close_period="2026-05",
        case_type="Mid-quarter upgrade + SLA credit",
        risk="High",
        status="Open",
        summary="Invoice appears overstated after mid-quarter Analytics upgrade and unapplied SLA credit.",
        lane_story="Main demo: amendment + SLA credit + revenue treatment",
        prompt="Review May close billing and revenue treatment for Acme. Check upgrade, invoice, SLA credit, and revenue policy.",
        invoice_total_cents=2_000_000,
        expected_invoice_total_cents=1_300_000,
        expected_decision="adjustment_required",
        expected_billing_adjustment_cents=-700_000,
        expected_revenue_adjustment_cents=-300_000,
        requires_approval=True,
        reason_codes=["analytics_overbilled", "approved_sla_credit_not_applied", "controller_review_required"],
        invoice_lines=[
            InvoiceLine("PROD-CORE", "Core Platform May 2026", 1_000_000, 1_000_000),
            InvoiceLine("PROD-SUPPORT", "Premium Support May 2026", 200_000, 200_000),
            InvoiceLine("PROD-ANALYTICS", "Analytics May 2026", 800_000, 400_000),
        ],
        revenue_schedule=[
            RevenueSchedule("Core Platform access", "2026-05", 1_000_000, 0, "system"),
            RevenueSchedule("Premium Support", "2026-05", 200_000, 0, "system"),
            RevenueSchedule("Analytics Module", "2026-05", 400_000, 0, "system"),
        ],
        evidence=[
            Evidence(
                "CC-ACME-001",
                "contract_clause",
                "Monthly billing terms",
                "Customer will be billed monthly in arrears for subscription services. Monthly subscription fees are calculated based on the annual contracted price divided by twelve unless an amendment states a different billing method.",
                "ACME-MSA-2026",
                "evidence://contract/CC-ACME-001",
            ),
            Evidence(
                "CC-ACME-002",
                "contract_clause",
                "Analytics upgrade effective date",
                "Analytics Module is added effective April 15, 2026. Fees are billed monthly at the annual Analytics price divided by twelve for full calendar months after activation.",
                "AMD-ACME-001",
                "evidence://contract/CC-ACME-002",
            ),
            Evidence(
                "CC-ACME-003",
                "contract_clause",
                "SLA service credit",
                "If monthly uptime for a subscribed module falls below 99.0%, Customer is entitled to a service credit equal to $3,000. Approved credits reduce the next open invoice for the affected module unless finance approves a different treatment.",
                "ACME-MSA-2026",
                "evidence://contract/CC-ACME-003",
            ),
            Evidence(
                "CR-ACME-SLA-05",
                "credit",
                "Approved SLA credit not applied",
                "Analytics outage credit approved for -$3,000 and still marked approved_not_applied against INV-ACME-2026-05.",
                "customer_credits",
                "evidence://credit/CR-ACME-SLA-05",
            ),
        ]
        + POLICIES,
        risk_signals=[{"signal_code": "HIGH_VALUE_ADJUSTMENT", "severity": "high", "reason": "Billing adjustment exceeds $2,500."}],
    ),
    Case(
        case_id="C2C-1002",
        customer="BetaCloud",
        customer_id="CUST-BETA",
        contract_id="CON-BETA-2026",
        invoice_id="INV-BETA-2026-05",
        close_period="2026-05",
        case_type="Clean renewal",
        risk="Low",
        status="Open",
        summary="Clean monthly renewal invoice matches contracted subscription terms.",
        lane_story="Deterministic rules should succeed",
        prompt="Review BetaCloud May renewal and confirm whether invoice and revenue schedule match.",
        invoice_total_cents=1_000_000,
        expected_invoice_total_cents=1_000_000,
        expected_decision="no_adjustment_required",
        expected_billing_adjustment_cents=0,
        expected_revenue_adjustment_cents=0,
        requires_approval=False,
        reason_codes=["invoice_matches_contract", "ratable_revenue_schedule_present"],
        invoice_lines=[InvoiceLine("PROD-CORE", "Core Platform May 2026", 1_000_000, 1_000_000)],
        revenue_schedule=[RevenueSchedule("Core Platform access", "2026-05", 1_000_000, 0, "system")],
        evidence=[
            Evidence("CC-BETA-001", "contract_clause", "Standard monthly subscription", "Core Platform is billed monthly at $10,000 and recognized ratably over the subscription period.", "BETA-MSA-2026", "evidence://contract/CC-BETA-001"),
            POLICIES[1],
        ],
    ),
    Case(
        case_id="C2C-1003",
        customer="Northstar Health",
        customer_id="CUST-NORTHSTAR",
        contract_id="CON-NORTHSTAR-2026",
        invoice_id="INV-NORTHSTAR-2026-05",
        close_period="2026-05",
        case_type="Side-letter concession",
        risk="High",
        status="Open",
        summary="Side letter concession appears allocated against the wrong line item.",
        lane_story="LLM needed: side letter language and allocation judgment",
        prompt="Review Northstar side letter concession and determine whether May invoice allocation is correct.",
        invoice_total_cents=3_150_000,
        expected_invoice_total_cents=3_300_000,
        expected_decision="reclass_adjustment_required",
        expected_billing_adjustment_cents=150_000,
        expected_revenue_adjustment_cents=0,
        requires_approval=True,
        reason_codes=["side_letter_concession_misallocated", "controller_review_required"],
        invoice_lines=[
            InvoiceLine("PROD-CORE", "Core Platform May 2026", 2_800_000, 3_000_000),
            InvoiceLine("PROD-IMPL", "Implementation services concession", 350_000, 300_000),
        ],
        evidence=[
            Evidence("CC-NORTHSTAR-001", "side_letter", "Commercial concession allocation", "For May through July 2026, a $2,000 monthly concession applies against Core subscription consideration only. The concession must not be applied against implementation services unless controller approval is documented.", "NORTHSTAR-SL-2026", "evidence://contract/CC-NORTHSTAR-001"),
            POLICIES[4],
            POLICIES[5],
        ],
        risk_signals=[{"signal_code": "AMBIGUOUS_CONCESSION", "severity": "high", "reason": "Side letter conflicts with invoice application."}],
    ),
    Case(
        case_id="C2C-1004",
        customer="MedNova Labs",
        customer_id="CUST-MEDNOVA",
        contract_id="CON-MEDNOVA-2026",
        invoice_id="INV-MEDNOVA-2026-05",
        close_period="2026-05",
        case_type="Usage overage approval",
        risk="Medium",
        status="Open",
        summary="Usage overage billed without required written approval.",
        lane_story="Clause interpretation controls billability",
        prompt="Review MedNova usage overage. Determine if May overage can be billed and recognized.",
        invoice_total_cents=1_400_000,
        expected_invoice_total_cents=1_000_000,
        expected_decision="billing_hold_required",
        expected_billing_adjustment_cents=-400_000,
        expected_revenue_adjustment_cents=-400_000,
        requires_approval=True,
        reason_codes=["usage_overage_exceeds_auto_bill_threshold", "written_approval_missing"],
        invoice_lines=[
            InvoiceLine("PROD-CORE", "Core Platform May 2026", 1_000_000, 1_000_000),
            InvoiceLine("PROD-USAGE", "API usage overage May 2026", 400_000, 0),
        ],
        usage=[Usage("PROD-USAGE", "api_calls", 2_000_000, 2_400_000, 400_000, 1, 400_000)],
        evidence=[
            Evidence("CC-MEDNOVA-001", "contract_clause", "Usage approval threshold", "API usage overage up to 10% above included quantity may be auto-billed. Overage above 10% requires written customer approval before billing or revenue recognition.", "MEDNOVA-MSA-2026", "evidence://contract/CC-MEDNOVA-001"),
            POLICIES[3],
            POLICIES[5],
        ],
    ),
    Case(
        case_id="C2C-1005",
        customer="OmniWorks",
        customer_id="CUST-OMNI",
        contract_id="CON-OMNI-2026",
        invoice_id="INV-OMNI-2026-ANNUAL",
        close_period="2026-05",
        case_type="Annual upfront billing",
        risk="High",
        status="Open",
        summary="Annual upfront billing was confused with immediately recognizable revenue.",
        lane_story="Billing vs revenue education",
        prompt="Review OmniWorks annual upfront invoice and May revenue recognition treatment.",
        invoice_total_cents=12_000_000,
        expected_invoice_total_cents=12_000_000,
        expected_decision="no_billing_adjustment_but_revenue_schedule_required",
        expected_billing_adjustment_cents=0,
        expected_revenue_adjustment_cents=-11_000_000,
        requires_approval=True,
        reason_codes=["upfront_billing_not_immediate_revenue", "ratable_schedule_required"],
        invoice_lines=[InvoiceLine("PROD-CORE", "Core Platform annual upfront 2026", 12_000_000, 12_000_000)],
        revenue_schedule=[RevenueSchedule("Core Platform access", "2026-05", 1_000_000, 12_000_000, "manual_upload")],
        evidence=[
            Evidence("CC-OMNI-001", "contract_clause", "Annual upfront billing", "Customer pays annual subscription fees upfront. Services are delivered continuously over the 12-month term.", "OMNI-MSA-2026", "evidence://contract/CC-OMNI-001"),
            POLICIES[0],
            POLICIES[1],
        ],
        risk_signals=[{"signal_code": "REVENUE_RECOGNITION_RISK", "severity": "high", "reason": "Full annual billing recognized in one month."}],
    ),
]


def get_case(case_id: str) -> Case:
    for case in CASES:
        if case.case_id == case_id:
            return case
    raise KeyError(case_id)

